# Generated by Django 4.1.6 on 2023-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма вклада'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='periods',
            field=models.PositiveSmallIntegerField(verbose_name='Период вклада'),
        ),
    ]
