# Generated by Django 4.1.6 on 2023-02-04 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_deposit', '0002_alter_deposit_amount_alter_deposit_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d\\d\\.\\d\\d\\.\\d{4}')], verbose_name='Дата вклада'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='periods',
            field=models.PositiveSmallIntegerField(verbose_name='Период вклада в месяцах'),
        ),
    ]
